language: objective-c
osx_image: xcode10.1
script:
    pod update
    set -o pipefail && xcodebuild -workspace ExampleProject.xcworkspace -scheme ExampleProject -destination 'platform=iOS Simulator,OS=12.1,name=iPhone X' build test | xcpretty
